version: '3.8'

services:
  frontend:
    build:
      context: ./source/frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # React sarà accessibile su http://localhost:3000
    depends_on:
      - db
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  # Il backend sarà accessibile su http://localhost:4000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=plateful_db
      - DB_USER=plateful_user
      - DB_PASSWORD=plateful

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: plateful_user
      POSTGRES_PASSWORD: plateful
      POSTGRES_DB: plateful_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/schemadb.sql:/docker-entrypoint-initdb.d/schemadb.sql:ro
    ports:
      - "5432:5432"

volumes:
  db_data:
